# Generated by Django 3.1.7 on 2026-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0037_create_default_visibility_for_existing_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
